### ISSUE TITLE
EAPI:Invalid key

### ISSUE THREAD

**Issue by yongyi520** [nothingisdead/npm-kraken-api#22]
I wrote the following code to set up a test sell order on kraken. However, the response that I got back from this code is: 'EAPI:Invalid key'

var param = {
      'pair': 'XXBTZEUR',
      'type': 'sell',
      'ordertype': 'limit',
      'price': '721.003',
      'volume': '.01'
    };
    kraken.api('AddOrder', param, function(error, data){
      if(error){
        console.log(error);
      } else {
        console.log(data.result);
      }
    });

I am sure that I got the right key since I can properly call and see the balance on my own account. 

Here is the screen capture of my key's permission: https://goo.gl/N5Cnp7. It has all the boxes checked except deposit and withdraw funds. 

I know this may not be coming from npm-kraken-api but kraken's. I just want to make sure :)

**Comment by rickyamu7** [comment]
Hi..I am facing same  issue in java..Did u got the issue solved..

**Comment by freshpatze** [comment]
I actually faced the same problem when using this API and for me it was due to an encoding issue. I found that using 'qs' instead of 'querystring' lib solved this for me, especially when it comes to nested objects. However, I don't really get why you are having these issues using above parameters..

**Comment by rickyamu7** [comment]
Hi, thanks for replying.I have tier 2 permissions and balance is zero.Is it
due to that.?is some money required for testing AddOrder or it gives
insufficient error

On 30-Apr-2017 11:22 PM, "Patrick Frischmann" <notifications@github.com>
wrote:

I actually faced the same problem when using this API and for me it was due
to an encoding issue. I found that using 'qs' instead of 'querystring' lib
solved this for me, especially when it comes to nested objects. However, I
don't really get why you are having these issues using above parameters..

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/nothingisdead/npm-kraken-api/issues/22#issuecomment-298246448>,
or mute the thread

**Comment by claude2** [comment]
Same problem with nested objects and the `qs` library fixed it. Example call that fails now:

```js
kraken.api('AddOrder', {
  pair: 'XXRPXXBT,
  type: 'buy',
  ordertype: 'limit',
  price: 0.1,
  volume: 10,
  close: {
    ordertype: 'limit',
    price: 0.2
  }
}, function (error, data) { ... });
```
